### ISSUE TITLE
Installation fails while getting durlwich (gcc missing)

### ISSUE THREAD

**Issue by shiosai** [python-poetry/install.python-poetry.org#29]
We replaced the deprecated script with the new one but now the installation fails because it tries to compile part of dulwich from scratch:
`Running setup.py install for dulwich: finished with status 'error'`
`error: command 'gcc' failed: No such file or directory`

The old script/poetry did not have this issue. We don't have gcc as this runs on some fixed docker image and it would be honestly a little bit overkill "just" to install poetry.

Would it help to install dulwich with the pure option?:
https://www.dulwich.io/downloads.html

**Comment by shiosai** [comment]
It works again when manually using an older poetry version (1.1.15 as in the old script) so probably this could be closed - despite problem exists with newer poetry versions

**Comment by neersighted** [comment]
This is not an issue with Poetry 1.2, but instead of your environment or Dulwich. Dulwich is installed by pip in the new installer, and pip is unable to find a wheel for your platform. You should either figure out what platform tags are needed for your environment and request Dulwich builds a wheel, or make sure you have a working C compiler as Dulwich requires one when built from sdist.

https://pypi.org/project/dulwich/#files
