### ISSUE TITLE
Poetry should not suggest to add `$HOME/.local/bin` to start of `PATH`.

### ISSUE THREAD

**Issue by vedal** [python-poetry/install.python-poetry.org#49]
A.k.a "poetry should play well with `pyenv`"

Currently, when installing `poetry` using the recommended installer, the following tip is printed at the end of installation.
> To get started you need Poetry's bin directory ($HOME/.local/bin) in your `PATH`
environment variable.
> Add `export PATH="$HOME/.local/bin:$PATH"` to your shell configuration file.

Having this made a huge [mess](https://github.com/pyenv/pyenv/issues/2417#issuecomment-1251062217) for me, as an old python2.7-pip was present in `$HOME/.local/bin/python2.7`, and happened to become default for all new venvs.

Maybe a better solution could be to just adding the poetry at the end of `PATH` instead, as:
> `export PATH="$PATH:$HOME/.local/bin"`

**Comment by neersighted** [comment]
The general advice is good -- and appending comes with its own bag of worms like being overridden by OS package manager copies or similar. I do tend to think that PATH management is generally out of scope here, and putting `$HOME/.local/bin` in front is likely to be more helpful as a default.

**Comment by vedal** [comment]
@neersighted maybe an option could be putting poetry inside a folder, such as `~/.local/bin/poetry/poetry`, and prepending only this path to PATH would avoid to add the rest of `~/.local/bin` to PATH?

**Comment by neersighted** [comment]
`$HOME/.local/bin` was selected as it's the default for the Python user site, and for pipx (as well as a well-known path that many users will have in their PATH already) -- I'm not sure there's a better default for most users than we have.

If you want to manually control where things go, `$POETRY_HOME/bin` will be used when you set `$POETRY_HOME` and can be prepended like you suggest. Otherwise you can create arbitrary symlinks to the `poetry` executable in the virtual environment if you want even more manual control.

**Comment by neersighted** [comment]
Also to be clear, the advice is not that this path should come strictly first in your PATH, but that something like it should be done. Putting it at the very front is best for newer users/simple use cases like pristine environments in CI as it will 'just work', but for more sophisticated users, you will have to do your own PATH management (e.g. controlling the contents of `$HOME/.local/bin`, putting pyenv in front of other sources of Python executables, etc.) and hopefully it's implicitly clear that Poetry doesn't do anything special and you'll have to manage it like any other PATH addition.

We could add language to make that a little more clear in the installer (e.g. add an `e.g.`) if you didn't find that obvious.

**Comment by vedal** [comment]
@neersighted thanks for your feedback. I think I understand your point that front or pack in PATH can both have its weaknesses. I'm pretty new to poetry still (started yesterday), so I might not have grasped the main use-case fully as designed yet (hope you'll forgive my ignorance then), but I thought it would be of greater importance to play well with a python version manager than CI "out-of-the-box", since setting up CI pipelines often requires its fair share of PATH know-how. In the case I described, the first encounter I had with poetry was that pyenv started using another pip-version, which should be unrelated and was fairly hard to debug (I didnt even consider that PATH couldve changed). 

However, these are of course just my five cents and my intent was to make it smoother for pyenv-users to adopt poetry. 
Maybe another solution could be advicing in the install-script to set $POETRY_HOME in .bash_profile, as you mention, like pyenv requires setting $PYENV_ROOT? That way, the order wont matter, and poetry will work without worrying what might be in .local/bin. What do you think? :)

**Comment by neersighted** [comment]
`$POETRY_HOME` is not actually something that needs to be set at runtime (as long as you get `$POETRY_HOME/bin` into the path somehow) for Poetry to work (though it is needed for self upgrade, I think)...

Pyenv doesn't call out anything about shell ordering, but I still think it is fairly obvious that things that need to take priority need to come later in the shell config as they all prepend by default (you can look at what `pyenv init -` does easily as it's just very simple shell script).

I think the main thing to keep in mind here is that Poetry is not doing anything special, it just puts a bin stub into the XDG user bin directory. If that directory is filled with garbage stubs, you'll run into issues, Poetry or no, if you ever make use of that bin path.

As to why this happens, it's not related to Poetry, pyenv, or pipx -- but instead Debian. Debian hotwires pip to default to `--user` installs which will place stubs into `site.getuserbase('scripts')` aka `$HOME/.local/bin` on Linux. When you `pip install --upgrade pip` what actually happens is a new, non-patched `pip` is installed to `site.getuserbase('purelib')`, shadowing the OS-provided copy (and the binstub is installed to the aforementioned 'scripts' path).

Debian is creating a confusing default/situation here by changing the defaults and causing this otherwise uncommon situation to become common. Ultimately the solution to "don't throw random pip stubs into `$HOME/.local/bin`" is to not create them by attempting to upgrade the system pip -- you're not interested in the system pip anyways as you're using pyenv now.

**Comment by neersighted** [comment]
I should also mention from the [XDG directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), there is this tidbit:

>  User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place.

Since $HOME might be shared between systems of different achitectures, installing compiled binaries to $HOME/.local/bin could cause problems when used on systems of differing architectures. This is often not a problem, but the fact that $HOME becomes partially achitecture-specific if compiled binaries are placed in it should be kept in mind. 

Part of why we choose this path is because it is a widespread standard (beyond the Python world) and nominally suggested by a cross-distro and cross-desktop-environment standard as a default PATH entry that should be present with no additional config. Obviously the world is Linux distributions is incredibly diverse and not every distro/environment follows this recommendation, but it is the closest thing to a cross-platform user-specific bin directory that exists.

We don't show a prompt to add it to the PATH if it's already detected in the PATH.

**Comment by vedal** [comment]
@neersighted I see. Thanks alot for the thorough explanation, it certainly helps to understand the interplay between tools and also Debian. And of course you're right that the intricacies of the python-world isnt poetry's fault. Maybe you're right that its safer to stick to the standard. An important reason for the mess was this useful remark you made:
> "... not create them by attempting to upgrade the system pip ..."

That's probably what I had done, some time or another, and then not thinking more about some .local/bin being somewhere at the back of PATH. It's probably a useful practice to keep the PATH clean, as you say.

Anyway, thanks again and I have all respect for people such as yourself who clearly are much more advanced than me in this field.

**Comment by flywire** [comment]
`Win10`

```
C:\>poetry --version
'poetry' is not recognized as an internal or external command,
operable program or batch file.

C:\>%APPDATA%\Python\Scripts\poetry --version
Poetry (version 1.2.1)
```

Install should make _some_ mention of `PATH`
