### ISSUE TITLE
Official installer failing

### ISSUE THREAD

**Issue by jaeger-2601** [python-poetry/install.python-poetry.org#68]
Python version: 3.10.5 (Installed using installer from python site)
OS: Windows 11

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue
I tried to install poetry using the official installing instructions i.e 
`Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -`
But got this error message during installation

``` 
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\Harshaa Vardaan\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.2)
Installing Poetry (1.2.2): Creating environment
Installing Poetry (1.2.2): An error occurred. Removing partial environment.
Poetry installation failed.
See C:\Users\(username)\poetry-installer-error-6aqwv0c_.log for error logs.
```

The contents of the error log file:

```
Unable to create process using 'C:\Users\(username)\AppData\Local\Programs\Python\Python310\python.exe -Im ensurepip --upgrade --default-pip'


Traceback:

  File "<stdin>", line 919, in main
  File "<stdin>", line 552, in run
```

**Comment by jaeger-2601** [comment]
Any updates on this issue?

**Comment by jaeger-2601** [comment]
@neersighted

**Comment by neersighted** [comment]
You have not provided sufficient detail to understand your environment or what is happening at this time, which is why I suspect no one has looked too closely at your issue yet. It seems likely that the Python binary in your Path is not functioning quite right -- I would start there. My next step would be inspecting a virtual environment created using that binary.

Please refrain from bumping issues without adding anything, and especially from pinging individuals for attention. We are all volunteers with limited time, and pinging individuals is likely to have the opposite effect of what you intend.

If you want to get an issue looked at faster, useful updates with additional context/information, debugging steps you have tried, and any research you may have attempted (including links) will help speed things up, as the next volunteer to glance at your issue will better understand it and have a head start in solving it (or in the case of this one, even have the faintest idea where to start, as it is so vague as to be non-helpful).

**Comment by neersighted** [comment]
Were you able to resolve this issue? What ended up being the root cause?

**Comment by jaeger-2601** [comment]
Nope. I simply switched over to pipenv.
